### PR TITLE
Add short markdown file with a link to OCX-Ruby example

### PR DESCRIPTION
**Pull request by paranoicsan**
Short link to instructions on how to consume or emit the data with OCX markup.

Скриншот 2019-03-14 16 38 54

Скриншот 2019-03-14 16 38 32

### CODE REVIEW

**Comment by philbarker** [comment]
Looks like useful content. Thanks

Is this to be linked in to the [existing documentation](https://k12ocx.github.io/k12ocx-specs/) in any way? 

As a standalone file it won't be part of the documentation  unless a line for it is added to mkdocs.yml .

But I think that until the list gets longer this text might be better added to /docs/index.md just before the section on IPR and License

**Comment by paranoicsan** [comment]
@philbarker thanks for the notice!

> As a standalone file it won't be part of the documentation unless a line for it is added to mkdocs.yml 

As I understood @jbaird123 he wanted a standalone file 😬 But I agree that's not useful at the moment. I think we can add the link to the index page itself as you proposed. @jbaird123 any input on this?

**Comment by jbaird123** [comment]
Let's add it to /docs/index.md as @philbarker suggested.  If there's a way to make it logically fit in the existing documentation as well by adding it to mkdocs.yml, that's a good idea too.

**Comment by paranoicsan** [comment]
I've added a link to the index page. And added screenshots to the PR body. Please review the changes 😄

**Comment by philbarker** [comment]
LGTM will merge unless @jbaird123 has any further comment

**Comment by jbaird123** [comment]
Looks good!  @philbarker - Go ahead!

**Pull request merged**
